mongo:
  label:
    name: mongodb-rs
  dbhost: mongodb
  dbport: 27017
  image: mongo:5.0
  volume:
    name: mongodb-volume
    mountPath: /data
    hostPath:  /data/mongodb-data
    node: k8s-node-03
orion:
  troe: true
  experimental: true
  port: 1026
  exposedPort: 80
  image: quay.io/fiware/orion-ld
  label:
    name: orion-ld-rs
  service:
    name: orion-ld-service
    hostname: orion.xip.io
  loglevel: DEBUG
postgis:
  label:
    name: postgisdb-rs
  dbhost: postgisdb
  dbport: 5432
  image: timescale/timescaledb-postgis:latest-pg12
  volume:
    name: postgisdb-volume
    mountPath: /var/lib/postgresql/data
    hostPath:  /data/timegis
    node: k8s-node-02

mintaka:
  label:
    name: mintaka-rs
  port: 8080
  exposedPort: 80
  image: quay.io/fiware/mintaka:latest
  service:
    name: mintaka-service
    hostname: orion.xip.io

