- hosts: "{{host | default('all')}}"
  become: true
  gather_facts: true
  tasks:
  - name: Update the /etc/hosts file with node name
    tags: etchostsupdate
    become: yes
    become_user: root
    lineinfile:
      regexp: ".*\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
      line: "{{ hostvars[item]['ansible_ens4']['ipv4']['address'] }}\t{{ hostvars[item]['ansible_hostname']}}"
      state: present
      backup: yes
      path: /etc/hosts
    register: etchostsupdate
    when: ansible_hostname != "{{ item }}" or ansible_hostname == "{{ item }}"
    with_items: "{{groups['all']}}"

